local M = {}

local config = require("fzf.config")

function M.setup(opts)
  config.setup(opts)
end

return M

-- local M = {}
-- M.config = {
--   files = {
--     fzf_opts = {
--       ["--exact"] = "",
--       ["--no-sort"] = "",
--     },
--   },
--
--   grep = {
--     fzf_opts = {
--       ["--exact"] = "",
--     },
--   },
-- }
--
-- function M.build_fzf_opts(opts)
--   local parts = {}
--
--   for key, value in pairs(opts or {}) do
--     if value == "" then
--       table.insert(parts, key)
--     else
--       table.insert(parts, key .. "=" .. value)
--     end
--   end
--
--   return table.concat(parts, " ")
-- end
--
-- M.fzf_base =
--     "fzf " ..
--     "--ansi " ..
--     "--layout=reverse " ..
--     "--height=100% " ..
--     "--border=none " ..
--     "--info=inline-right " ..
--     "--prompt='󰍉  ' " ..
--     "--pointer='▶' " ..
--     "--marker='✓' " ..
--     "--separator='─' " ..
--     "--scrollbar='│' " ..
--     "--preview-window='right:60%:border-left' "
--
-- M.bat_preview =
-- "bat --color=always --style=numbers"
--
--
-- function M.notify(msg, level)
--   vim.notify(msg, level or vim.log.levels.INFO)
-- end
--
-- function M.jump(filepath, line, col)
--   vim.cmd("hide edit " .. vim.fn.fnameescape(filepath))
--
--   local l = tonumber(line) or 1
--   local c = tonumber(col) or 1
--
--   pcall(vim.api.nvim_win_set_cursor, 0, { l, c - 1 })
--
--   vim.cmd("normal! zz")
-- end
--
-- function M.get_size()
--   local width = math.floor(vim.o.columns * 0.90)
--   local height = math.floor(vim.o.lines * 0.65)
--
--   return width, height
-- end
--
-- function M.create_backdrop()
--   local buf = vim.api.nvim_create_buf(false, true)
--
--   local win = vim.api.nvim_open_win(buf, false, {
--     relative = "editor",
--     width = vim.o.columns,
--     height = vim.o.lines,
--     row = 0,
--     col = 0,
--     focusable = false,
--     style = "minimal",
--     zindex = 1,
--   })
--
--   vim.api.nvim_set_hl(0, "MyFzfBackdrop", {
--     bg = "#000000",
--     default = false,
--   })
--
--   vim.api.nvim_win_set_option(win, "winhighlight",
--     "Normal:MyFzfBackdrop")
--
--   vim.api.nvim_win_set_option(win, "winblend", 70)
--
--   return win
-- end
--
-- function M.fzf_ui(cmd, on_select)
--   local backdrop = M.create_backdrop()
--
--   local buf = vim.api.nvim_create_buf(false, true)
--
--   local width, height = M.get_size()
--
--   local row = math.floor((vim.o.lines - height) / 2)
--   local col = math.floor((vim.o.columns - width) / 2)
--
--   local win = vim.api.nvim_open_win(buf, true, {
--     relative = "editor",
--     width = width,
--     height = height,
--     row = row,
--     col = col,
--     border = {
--       "╭", "─", "╮",
--       "│", "╯", "─",
--       "╰", "│",
--     },
--     style = "minimal",
--     zindex = 50,
--     title = " FZF ",
--     title_pos = "center",
--     footer = " esc to close ",
--     footer_pos = "right",
--   })
--
--   vim.api.nvim_win_set_option(win, "winblend", 0)
--
--   vim.api.nvim_set_option_value(
--     "winhighlight",
--     "Normal:NormalFloat,FloatBorder:FloatBorder",
--     { win = win }
--   )
--
--   local root = vim.fn.getcwd()
--
--   local temp = vim.fn.tempname()
--
--   local full_cmd = string.format(
--     "cd %s && %s > %s",
--     vim.fn.shellescape(root),
--     cmd,
--     vim.fn.shellescape(temp)
--   )
--
--   vim.fn.termopen(
--     { "sh", "-c", full_cmd },
--     {
--       on_exit = function(_, code)
--         vim.schedule(function()
--           if vim.api.nvim_win_is_valid(win) then
--             vim.api.nvim_win_close(win, true)
--           end
--
--           if vim.api.nvim_win_is_valid(backdrop) then
--             vim.api.nvim_win_close(backdrop, true)
--           end
--
--           if code == 0 and vim.fn.filereadable(temp) == 1 then
--             local f = io.open(temp, "r")
--
--             if f then
--               local selection = f:read("*all"):gsub("\n$", "")
--
--               f:close()
--
--               os.remove(temp)
--
--               if selection ~= "" then
--                 on_select(selection, root)
--               end
--             end
--           else
--             if vim.fn.filereadable(temp) == 1 then
--               os.remove(temp)
--             end
--           end
--         end)
--       end,
--     }
--   )
--
--   vim.keymap.set("t", "<Esc>", function()
--     if vim.api.nvim_win_is_valid(win) then
--       vim.api.nvim_win_close(win, true)
--     end
--
--     if vim.api.nvim_win_is_valid(backdrop) then
--       vim.api.nvim_win_close(backdrop, true)
--     end
--   end, {
--     buffer = buf,
--     nowait = true,
--   })
--
--   vim.cmd("startinsert")
-- end
--
-- M.sessions_dir = vim.fn.expand("~/.local/share/nvim/sessions")
-- vim.fn.mkdir(M.sessions_dir, "p")
--
-- local harpoon_file = vim.fn.stdpath("data") .. "/harpoon.json"
-- local git_root_cache = {}
--
-- function M.get_git_root()
--   local cwd = vim.fn.getcwd()
--   if git_root_cache[cwd] then
--     return git_root_cache[cwd]
--   end
--
--   local root_result = vim.fn.systemlist("git rev-parse --show-toplevel 2>/dev/null")
--   local root
--   if vim.v.shell_error == 0 and root_result[1] and not root_result[1]:match("^fatal") then
--     root = root_result[1]
--   else
--     root = cwd
--   end
--
--   git_root_cache[cwd] = root
--   return root
-- end
--
-- function M.harpoon_load()
--   local f = io.open(harpoon_file, "r")
--   if not f then return {} end
--   local content = f:read("*all")
--   f:close()
--   local ok, data = pcall(vim.fn.json_decode, content)
--   return (ok and data) or {}
-- end
--
-- function M.harpoon_save(data)
--   local f = io.open(harpoon_file, "w")
--   if f then
--     f:write(vim.fn.json_encode(data))
--     f:close()
--   end
-- end
--
-- function M.harpoon_jump(index)
--   local files = (M.harpoon_load())[M.get_git_root()]
--   if files and files[index] then vim.cmd("edit " .. vim.fn.fnameescape(files[index])) end
-- end
--
-- return M
