local helpers = require("fzf.helpers")

describe("helpers", function()
  describe("file_icon", function()
    it("returns icon for known extension", function()
      local icon = helpers.file_icon("test.lua")
      assert.equals("", icon)
    end)

    it("returns default icon for unknown extension", function()
      local icon, color = helpers.file_icon("test.xyz")
      assert.equals("", icon)
      assert.is_nil(color)
    end)

    it("matches by basename for extensionless files", function()
      local icon = helpers.file_icon("Makefile")
      assert.equals("", icon)
    end)
  end)

  describe("strip_icon", function()
    it("strips icon and separator from line", function()
      local result = helpers.strip_icon("\ttest.lua")
      assert.equals("test.lua", result)
    end)
  end)

  describe("join_path", function()
    it("joins root and file", function()
      assert.equals("/root/file", helpers.join_path("/root", "file"))
    end)

    it("handles trailing slash in root", function()
      assert.equals("/root/file", helpers.join_path("/root/", "file"))
    end)

    it("handles leading slash in file", function()
      assert.equals("/root/file", helpers.join_path("/root", "/file"))
    end)
  end)

  describe("add_file_icons", function()
    it("adds icons to a list of files", function()
      local result = helpers.add_file_icons({ "test.lua", "test.md" })
      assert.equals(2, #result)
      assert.is_true(result[1]:match("^."))
    end)
  end)

  describe("build_fzf_opts", function()
    it("converts opts table to string", function()
      local result = helpers.build_fzf_opts({ ["--exact"] = "", ["--no-sort"] = "" })
      assert.is_true(result:match("%-%-exact"))
      assert.is_true(result:match("%-%-no%-sort"))
    end)

    it("handles key-value opts", function()
      local result = helpers.build_fzf_opts({ ["--prompt"] = "> " })
      assert.is_true(result:match(">"), "should include value")
    end)
  end)
end)
